spring:
  aop:
    proxyTargetClass: true
  application:
    name: api-gateway-service

server:
  port: 8071

security:
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlD7P37ECba1eKH+Ipd4p
          wL8n5g7VDivCYaMcPf9j8pXBY0rC2kDmG+d23Tsd+ANwQqeWlo22OXBPbVqruEPM
          zIgW4tf2qm1S3CUrXfcI1B3ves8yHc692xE4urwkToGpmh42Vo1tsp6uoGYYZZQe
          y3WsZ5rZEvaIE+qO/W0X3Bj6YMwg5jRqKszdWkiZTrJcYGroLJ0cbOFZyhT+U54k
          uTro4eG49gg8ilrJq2Qj+ltVJPAz8zFfoQqLx2/jEY9DMiYp7BqdUu77G1SN3wbq
          2bdpPNGcOmLk4h/0QKfB9t/uV2nWYP0R/7xIeHbRdmzypHtXIuBIDqQg2WDecHhD
          AQIDAQAB
          -----END PUBLIC KEY-----

eureka:
  instance:
    hostname: localhost
    #hostname: runtime-registry
    port: 8070
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:

  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /api
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service

    appointment-service:
      path: /appointment/**
      serviceId: appointment-service

    friseur-information-service:
      path: /customerinfos/**
      serviceId: friseur-information-service

    customer-service:
      path: /customer/**
      serviceId: customer-service

    partner_service:
      path: /partner/**
      serviceId: partner-service

    user_service:
      path: /user/**
      serviceId: user-service

    authentication_service:
      sensitiveHeaders: Authorization
      path: /auth/**
      serviceId: authentication-service

  add-proxy-headers: true

logging:
  level.org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
